### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by WindLeaf233** [rong862/bear#1]
大佬能做评论变色功能吗

**Comment by sudami** [comment]
> 大佬能做评论变色功能吗

比翼多开支持评论变色，免ROOT的
![A%G{~363{2(POM%BT8Q@P)O](https://user-images.githubusercontent.com/6194926/198865227-ea7e2b93-404a-4d1f-9041-51eec87ec2fc.jpg)
![EGZNM5~9OS3R`0{17_{X9FJ](https://user-images.githubusercontent.com/6194926/198865247-381a61ed-1ebd-452e-b872-ce5f2011aec0.png)

下载链接： 
https://sudami.lanzoul.com/bydknew
https://www.123pan.com/s/fVlKVv-tJ3Fv

**Comment by WindLeaf233** [comment]
> > 大佬能做评论变色功能吗
> 
> 比翼多开支持评论变色，免ROOT的 ![A%G{~363{2(POM%BT8Q@P)O](https://user-images.githubusercontent.com/6194926/198865227-ea7e2b93-404a-4d1f-9041-51eec87ec2fc.jpg) ![EGZNM5~9OS3R`0{17_{X9FJ](https://user-images.githubusercontent.com/6194926/198865247-381a61ed-1ebd-452e-b872-ce5f2011aec0.png)
> 
> 下载链接： [sudami.lanzoul.com/bydknew](https://sudami.lanzoul.com/bydknew) [123pan.com/s/fVlKVv-tJ3Fv](https://www.123pan.com/s/fVlKVv-tJ3Fv)

非常感谢！！
