### ISSUE TITLE
关于解析

### ISSUE THREAD

**Issue by 666HailSatan666** [rong862/bear#101]
我在微信小程序里找了那种能解析无水印的视频  但是他就不会压缩你可以试一下  有一个叫万能去水印的紫色图标的

**Comment by 666HailSatan666** [comment]
辛苦作者了要是有个tg群交流就更好了  之前加你QQ你也没同意  要是能做个tiktok解析就更好了

**Comment by rong862** [comment]
跟那种网页解析的原理不一样，交流可以入扣扣群： 110430929
