### ISSUE TITLE
抖音版本24.5 本地收藏表情包不能直接下载

### ISSUE THREAD

**Issue by LHC12580** [rong862/bear#102]
麻烦作者更新下一下。谢谢。

**Comment by rong862** [comment]
已经添加了收藏表情包下载

**Comment by LHC12580** [comment]
好的，我去看看，好像是动态图片不能收藏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rong862/bear] 抖音版本24.5 本地收藏表情包不能直接下载 (Issue #102)




 
已经添加了收藏表情包下载

**Comment by LHC12580** [comment]
大佬，表情包下载只有静态图片可以下载，评论区的动态图片，还有收藏的GIF图片不能下载！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rong862/bear] 抖音版本24.5 本地收藏表情包不能直接下载 (Issue #102)




 
已经添加了收藏表情包下载
