### ISSUE TITLE
作者还是没有"不喜欢"的按钮嘛

### ISSUE THREAD

**Issue by ec-to** [rong862/bear#108]
控件id，不知道能不能帮上忙。

图标
![Screenshot_2023-10-27-19-34-47-67_2332cb9b27b851b548ba47a91682926c](https://github.com/rong862/bear/assets/24844835/08370f8a-f84f-4da4-81fc-eb89abfe5b2f)

文字
![Screenshot_2023-10-27-19-34-54-79_2332cb9b27b851b548ba47a91682926c](https://github.com/rong862/bear/assets/24844835/f0a6cecb-d07e-4750-8c2c-72a1b364ef5b)

整个框
![Screenshot_2023-10-27-19-34-51-76_2332cb9b27b851b548ba47a91682926c](https://github.com/rong862/bear/assets/24844835/a5239a80-95c9-4d9c-a613-881be92418cc)

**Comment by huanfe1** [comment]
遇到同样问题，希望可以添加一个隐藏不喜欢按钮的选项

**Comment by rong862** [comment]
这个控件id每个版本都不一样，不好弄

**Comment by rong862** [comment]
更新07版本已添加
