### ISSUE TITLE
模块被侦测到  帐号无法登入

### ISSUE THREAD

**Issue by SkillGodAk** [rong862/bear#125]
现在只要安装小能手
帐号都会不给登入
只允许原版没修改过的
才能登入帐号

![4989](https://github.com/rong862/bear/assets/104513085/18e38d40-4840-4d48-a8b8-86c920cc1044)

**Comment by Mubai-meng** [comment]
这跟模块没关系，签名效验的问题

**Comment by Mubai-meng** [comment]
> > 这跟模块没关系，签名效验的问题
> 
> 要怎麽绕过?之前没这个问题

过签，或者等最近风头过去

**Comment by SkillGodAk** [comment]
> 过签

试过了，ｌｖ１　ｌｖ２过签都还是不行

**Comment by Mubai-meng** [comment]
> > 过签
> 
> 试过了，ｌｖ１　ｌｖ２过签都还是不行

跟v1v2没关系，要手撕签验，一般人搞不了，现在是服务器验证，等风头过了或采取其他办法

**Comment by SkillGodAk** [comment]
> > > 过签
> > 
> > 
> > 试过了，ｌｖ１　ｌｖ２过签都还是不行
> 
> 跟v1v2没关系，要手撕签验，一般人搞不了，现在是服务器验证，等风头过了或采取其他办法

明白了，谢谢大大回答
