### ISSUE TITLE
只剩画面或者黑屏

### ISSUE THREAD

**Issue by xxnuo** [rong862/bear#128]
功能全开，除了隐藏状态栏
刷几个视频后所有按钮都会消失![Screenshot_2023-11-16-18-24-15-532_com.ss.android.ugc.aweme.jpg](https://github.com/rong862/bear/assets/54252779/acd1b086-3501-4253-8236-b973b9eddf93)

双击打开评论区后
![Screenshot_2023-11-16-18-24-19-341_com.ss.android.ugc.aweme.jpg](https://github.com/rong862/bear/assets/54252779/1bc9253f-343f-4ce2-b8f1-f4b2ef584ec4)

**Comment by xxnuo** [comment]
透明度都是 45%，没有调到完全透明

**Comment by rong862** [comment]
清除一下数据，模块没改过这些
