### ISSUE TITLE
最新抖音不适配麻烦大佬更新一下

### ISSUE THREAD

**Issue by Fabali** [rong862/bear#131]
抖音版本 27.7.0(270701)
在app内没反应，麻烦大佬适配一下

**Comment by rong862** [comment]
清除app数据重新适配

**Comment by Fabali** [comment]
> 清除app数据重新适配

好的

**Comment by OUYANG777** [comment]
我的27.0.0版本不会弹出适配界面，清除几次还是一样，分享里面也没有😭

**Comment by Fabali** [comment]
> 我的27.0.0版本不会弹出适配界面，清除几次还是一样，分享里面也没有😭

27.7.0 ? 我在lsp里面重新优化了一下，然后重启手机就可以了，你可以试试

**Comment by rong862** [comment]
这种问题清除APP数据可解决
