### ISSUE TITLE
自动播放按钮太大了，影响观看

### ISSUE THREAD

**Issue by shizhen1122** [rong862/bear#156]
![Screenshot_2023-12-28-12-22-09-906_com ss android ugc aweme](https://github.com/rong862/bear/assets/100275224/90e05408-73eb-4e8f-990f-4658a235aefe)

**Comment by kof8855** [comment]
为什么你还能用？我现在一登陆就提示版本问题 不给我登陆账号了。哪个版本的抖音+小能手？手机root了？用的面具？

**Comment by YunnrEX** [comment]
> 为什么你还能用？我现在一登陆就提示版本问题 不给我登陆账号了。哪个版本的抖音+小能手？手机root了？用的面具？

好像能通过卡断网进行登录，具体方法去查吧，我用的root，最近也有毛病，开了模块后经常闪退

**Comment by oyal** [comment]
我为了查看年度报告，把之前的卸载了，再装发现没法登录了

**Comment by shizhen1122** [comment]
> 为什么你还能用？我现在一登陆就提示版本问题 不给我登陆账号了。哪个版本的抖音+小能手？手机root了？用的面具？

抖音版本25.9.0 抖音助手v2.0.6
根据我的测试，你安装完之后不要先适配，先去登录账号。登陆完之后再去lsp里面重启一下模块，再进入抖音适配就可以了

**Comment by oyal** [comment]
我发现能登录了。逗音小助手 v2.0.7 一个自动播按钮太大太丑了，评论区也不能保存图片

**Comment by kof8855** [comment]
> 我发现能登录了。逗音小助手 v2.0.7 ~一个自动播按钮太大太丑了，评论区也不能保存图片~
> 
> 重启了一下自动播放按钮变小了(不知道如何隐藏这个按钮)，评论区也能保存图片了，之前一直提示不支持此类视频

真的能登录了？我还是登录不了，还显示非官方客户端

**Comment by kof8855** [comment]
> 引用到新议

6666这个版本还真能登录

**Comment by kof8855** [comment]
> freedom+

好想freedom+这个模块用不了呢，不知道怎么用

**Comment by oyal** [comment]
> > freedom+
> 
> 好想freedom+这个模块用不了呢，不知道怎么用

我也不知道怎么用，看上去很多功能和小助手都重叠了

**Comment by kof8855** [comment]
> > > freedom+
> > 
> > 
> > 好想freedom+这个模块用不了呢，不知道怎么用
> 
> 我也不知道怎么用，看上去很多功能和小助手都重叠了

知道怎么用了，点开左上角的三条杠，里面有常用小程序、常用功能等，往下划到最下面有一个扩展功能就看到reedom+，点开就能打开各种功能了，我看默认都是关闭的

**Comment by oyal** [comment]
> > > > freedom+
> > > 
> > > 
> > > 好想freedom+这个模块用不了呢，不知道怎么用
> > 
> > 
> > 我也不知道怎么用，看上去很多功能和小助手都重叠了
> 
> 知道怎么用了，点开左上角的三条杠，里面有常用小程序、常用功能等，往下划到最下面有一个扩展功能就看到reedom+，点开就能打开各种功能了，我看默认都是关闭的

对，我也发现了，所以我说一些功能重复了，打开开关好像也没啥效果emm。你知道小助手那个“自动播”按钮如何隐藏吗？

**Comment by kof8855** [comment]
> > > > > freedom+
> > > > 
> > > > 
> > > > 好想freedom+这个模块用不了呢，不知道怎么用
> > > 
> > > 
> > > 我也不知道怎么用，看上去很多功能和小助手都重叠了
> > 
> > 
> > 知道怎么用了，点开左上角的三条杠，里面有常用小程序、常用功能等，往下划到最下面有一个扩展功能就看到reedom+，点开就能打开各种功能了，我看默认都是关闭的
> 
> 对，我也发现了，所以我说一些功能重复了，打开开关好像也没啥效果emm。你知道小助手那个“自动播”按钮如何隐藏吗？

UI设置里面有“主页添加自动播放按钮”
