### ISSUE TITLE
新版本的，控件可以考虑再加几个吗

### ISSUE THREAD

**Issue by musongsky** [rong862/bear#16]
![Screenshot_2023-04-04-17-04-56-834_com ss android ugc aweme](https://user-images.githubusercontent.com/58104794/229743807-e45e33d1-410a-4fcc-88d8-e4de62d12a29.jpg)
左上角加号，反馈，和右边的不感兴趣，唱片这几个

**Comment by rong862** [comment]
这种太个性化的你得找人去定制，这个不考虑
