### ISSUE TITLE
LSPatch无法登录可以尝试更改内置的签名试试

### ISSUE THREAD

**Issue by hanximeng** [rong862/bear#178]
LSPatch内嵌模块之前一登录就提示非官方，今天试着修改了LSPatch内置的签名，发现可以正常登录了。

**Comment by Cjxlzjr** [comment]
> LSPatch内嵌模块之前一登录就提示非官方，今天试着修改了LSPatch内置的签名，发现可以正常登录了。

具体怎么操作啊,能讲讲吗大佬

**Comment by ddgod-lf** [comment]
> LSPatch内嵌模块之前一登录就提示非官方，今天试着修改了LSPatch内置的签名，发现可以正常登录了。

请教如何操作，谢谢 @hanximeng

**Comment by hanximeng** [comment]
LSPatch有自定义签名密钥的功能自行寻找具体位置即可
