### ISSUE TITLE
今天突然沉浸式状态栏失效

### ISSUE THREAD

**Issue by elkesonupup** [rong862/bear#187]
coloros14系统的一加12，和coloros13.1的一加ACE2，全都无法使用透明状态栏。之前一加12一直正常使用，今天突然要重新适配，然后透明状态栏就失效了![Screenshot_2024-04-09-19-13-18-09_bf947da166bbb3f0571601a1cf656e6f.jpg](https://github.com/rong862/bear/assets/160863588/0c6dc0a6-f698-4751-8bfe-3b16882a8a5f)

![Screenshot_2024-04-09-19-13-39-34_bf947da166bbb3f0571601a1cf656e6f.jpg](https://github.com/rong862/bear/assets/160863588/358faf0f-83e9-4db9-bf24-8814218cbfba)

**Comment by rong862** [comment]
update
