### ISSUE TITLE
求修复推荐 虽然不是很重要

### ISSUE THREAD

**Issue by 2551784204** [rong862/bear#189]
https://github.com/rong862/bear/assets/167889519/1bc0020d-3729-4169-83c9-616898522d68

**Comment by MvBox** [comment]
你把那个朋友推荐删掉试试
![Uploading Screenshot_2024-04-26-04-15-53-060_com.ss.android.ugc.aweme.jpg…]()

**Comment by MvBox** [comment]
删掉朋友推荐
![Uploading Screenshot_2024-04-26-04-15-53-060_com.ss.android.ugc.aweme.jpg…]()

**Comment by MvBox** [comment]
其他设置→提示框屏蔽→删掉朋友推荐即可
