### ISSUE TITLE
192版本，底栏透明度调整的问题

### ISSUE THREAD

**Issue by chenxiccc** [rong862/bear#20]
1 底栏透明度调整，调整的是底部的作者名以及文字介绍的透明度，而不是底部 首页 朋友 加号 消息 我的，这几个的透明度。
请问：这是不是个问题？

如果不是问题，建议菜单文案可略做调整，比如可考虑“底部文案区透明度调整”。

2 当前192版本是不是还没有调整底部“首页/朋友/加号/消息/我的”这个底部区域的透明度功能？
看起来透明度变了，但是设置菜单中却没有找到相应的设置。

**Comment by rong862** [comment]
底栏指的就是文案那一块，底部选项卡文字没调整；
