### ISSUE TITLE
亲，能加上长按弹出评论框吗

### ISSUE THREAD

**Issue by a857112551** [rong862/bear#21]
亲，能加上长按弹出评论框吗，这个真是刚需啊。一般都是左手用手机，点评论比较费劲

**Comment by rong862** [comment]
已增加双击打开

**Comment by a857112551** [comment]
感谢，但是双击点赞还是很需要的
![0013CF4A](https://user-images.githubusercontent.com/18694613/232766408-6896bc94-d3fc-41b8-8d91-3127106935c7.png)
，还有能不能加上过滤掉直播的功能，
![0014F8F5](https://user-images.githubusercontent.com/18694613/232766711-022a5a38-c4d5-4e13-85ba-aefab5121a28.png)

**Comment by natsu1949** [comment]
> 已增加双击打开

跟点赞冲突了😩，感觉长按更好用点
