### ISSUE TITLE
最新版抖音适配

### ISSUE THREAD

**Issue by a519293149** [rong862/bear#23]
在最新版的抖音中适配出现了问题，以前的设置还可以继续使用，但功能列表在分享按键里不再显示了，期待尽快更新

**Comment by rong862** [comment]
更新最新版

**Comment by a519293149** [comment]
抖音版本25.1.0
助手版本1.9.2
刚刚更新适配后在分享里还是不显示功能按键，且部分之前设置的功能失效。
例如:不显示主页“➕”号，现在显示了

**Comment by a519293149** [comment]
抱歉，是我的问题，我刚才没有更新小助手至1.9.4版本，现在可以了，全部恢复正常
