### ISSUE TITLE
适配不成功

### ISSUE THREAD

**Issue by Raudience** [rong862/bear#25]
iqoo7 安卓13 lsp1.8.6（6872）zygisk
抖音25.0.0 抖音小能手1.9.4
每次打开都提示发现新版本，点击适配之后说重启生效，重启之后还提示发现新版本😭

**Comment by soyuzom** [comment]
给 文件和媒体 读写权限没有？

**Comment by Raudience** [comment]
给不了，不管是系统自带的应用管理，还是爱玩机工具箱中的应用权限管理，都找不到“文件和媒体 读写权限”或者类似权限
