### ISSUE TITLE
亲，双击点赞还是很需要的，还有能不能加上过滤掉直播的功能

### ISSUE THREAD

**Issue by a857112551** [rong862/bear#26]
感谢，但是双击点赞还是很需要的![0013CF4A](https://user-images.githubusercontent.com/18694613/232766408-6896bc94-d3fc-41b8-8d91-3127106935c7.png)，还有能不能在播放列表里面加上过滤掉直播的功能，![0014F8F5](https://user-images.githubusercontent.com/18694613/232766711-022a5a38-c4d5-4e13-85ba-aefab5121a28.png)

**Comment by rong862** [comment]
更新最新版
