### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by 2271059753** [rong862/bear#29]
表情包下载本地无效，25.1版本主页顶栏标签隐藏失效
![Screenshot_2023-04-26-12-47-23-26_2332cb9b27b851b548ba47a91682926c.jpg](https://user-images.githubusercontent.com/84062350/234472469-8cc1304e-ba85-4f98-862b-8150dd0a4a08.jpg)

![Screenshot_2023-04-26-12-46-53-35_2332cb9b27b851b548ba47a91682926c.jpg](https://user-images.githubusercontent.com/84062350/234472477-3ad8b8f8-d6cc-41aa-bf06-020cefc4e7f2.jpg)

**Comment by rong862** [comment]
重启

**Comment by mirabel063** [comment]
25.2底栏透明和隐藏失效，重启无效。其他暂时正常。
