### ISSUE TITLE
能加极速性能模式吗

### ISSUE THREAD

**Issue by yaohuo365** [rong862/bear#31]
太臃肿了，占运存，希望加个极速性能模式。

**Comment by rong862** [comment]
这玩意能占你几个内存？ 怎么个极速性能模式

**Comment by yaohuo365** [comment]
> 这玩意能占你几个内存？ 怎么个极速性能模式

原先的土拔鼠和lanfeng都有性能模式。我8g运存剩4.6g开抖音后只剩2g多，发烫。

**Comment by Mubai-meng** [comment]
> 这玩意能占你几个内存？ 怎么个极速性能模式

![Screenshot_2023-05-29-10-53-33-242_bin.mt.plus.jpg](https://github.com/rong862/bear/assets/86759349/0c30ea83-c4bd-4736-b737-74224cd61651)

官方针对低端机有个性能模式，可以关闭一些不必要的功能达到降低发热卡顿及省电的作用，但这个功能是自动的，如果可以强开就好了
