### ISSUE TITLE
评论区图片还有视频下载有问题

### ISSUE THREAD

**Issue by dpc011019** [rong862/bear#52]
官方给新版抖音评论区图片右上角加了一个“我也发一张”刚好把下载按钮挡了，还有评论区视频下载，明明下载的是第一楼的，结果把第二楼的视频下载了，得重试几次，大佬排查一下

**Comment by dpc011019** [comment]
![Uploading IMG_20230613_140703.jpg…]()

**Comment by rong862** [comment]
更新2.0版本
