### ISSUE TITLE
有些视频会进行放大播放，可不可以让ta原比列播放

### ISSUE THREAD

**Issue by l666l** [rong862/bear#56]
放大后视屏中文字会显示不全

**Comment by rong862** [comment]
把状态栏透明关闭就可以原比例。

**Comment by l666l** [comment]
okk,另外一个小问题就是抖音下方四个选项(首页，朋友，消息，我)不能改变透明度

**Comment by rong862** [comment]
这个本身就没有这个功能；

**Comment by l666l** [comment]
大佬能加个这功能把那四大金刚也给弄成可调透明度不😃

**Comment by l666l** [comment]
还有就是现在不能登录账号，登录就锁定了，大神能不能把这个也优化一下

**Comment by rong862** [comment]
没操作过账号相关的东西，应该不是这个引起的。
