### ISSUE TITLE
25.90透明状态栏失效

### ISSUE THREAD

**Issue by xiang473535976** [rong862/bear#57]
1.抖音版本25.90
2.确定开启了透明状态栏
3.多次重新视频，卸载安装都不透明
4.模块版本用的大佬最新的2.0.0

能否说下大佬你要哪个的哪个版本，或者是最高支持到哪个版本。
![Screenshot_2023-06-19-15-16-25-479_com ss android](https://github.com/rong862/bear/assets/18111614/fbadcfb9-34b9-4483-b0ad-74ef89c69430)

**Comment by rong862** [comment]
更新版本
