### ISSUE TITLE
视频下载清晰度过低

### ISSUE THREAD

**Issue by 2478641181** [rong862/bear#62]
原视频1080p 60帧 双声道下载只有720p30帧 音频单声道

**Comment by 2478641181** [comment]
> 原视频1080p 60帧 双声道下载只有720p30帧 音频单声道

@rong862 帮您搭建了一个api是原画质的 您看下改吗
http://124.220.15.161/

**Comment by rong862** [comment]
现在不是走的第三方api

**Comment by 2478641181** [comment]
> 现在不是走的第三方api

但不知道为何下载清晰度很低

**Comment by 666HailSatan666** [comment]
确实  评论区的表情也会失真
