### ISSUE TITLE
更新了26.2后，不提示适配，分享之后也不见模块入口。回退到26.0抖音➕逗音2.0.0也不行。求解决。

### ISSUE THREAD

**Issue by job-ma-ook** [rong862/bear#65]
更新了26.2后，不提示适配，分享之后也不见模块入口。回退到26.0抖音➕逗音2.0.0也不行。求解决。
![S30716-19340842_com ss android ugc aweme](https://github.com/rong862/bear/assets/54350591/c3128aeb-ca42-40ac-bac6-735a32670099)

**Comment by rong862** [comment]
清除软件数据

**Comment by Ghd-0802** [comment]
> 清除软件数据

我也在一个多月前遇到了不提示适配的情况, 是因为那次弹窗提示我适配 我不小心点什么地方关掉了弹框,就再也不提示我适配了,我清理了抖音和小助手的全部缓存 都是不提示我适配

**Comment by Ghd-0802** [comment]
> > 清除软件数据
> 
> 我也在一个多月前遇到了不提示适配的情况, 是因为那次弹窗提示我适配 我不小心点什么地方关掉了弹框,就再也不提示我适配了,我清理了抖音和小助手的全部缓存 都是不提示我适配

我解决了这个问题,
通过修改判断,前置弹出适配框,适配后,重新装回原版,问题得到解决
`        if (!g.f2453h.d("CUR_VER").equals(g.f2451f)) {
            if (g.f2453h.a("IS_SEARCH")) {
                return;
            }
            g.f2453h.f("IS_SEARCH", true);
            c.c("【APP】", "发现新版本，弹出适配对话框！");
            new q().c();
            return;
        }
`
