### ISSUE TITLE
大佬能否增加最低为7.0版本？不然下载连安装按钮都没有🤐

### ISSUE THREAD

**Issue by berebrn** [rong862/bear#74]
![Screenshot_2023-08-21-06-44-20-810_de robv android xposed installer](https://github.com/rong862/bear/assets/140738041/a766c5c6-b92e-4623-8894-ae13663a5787)
![Screenshot_2023-08-21-06-43-58-864_bin mt plus](https://github.com/rong862/bear/assets/140738041/8464e78f-926c-47ca-b833-cd92929a46a5)

**Comment by rong862** [comment]
太低了支持不了，该换手机了
