### ISSUE TITLE
抖音的不喜欢按钮

### ISSUE THREAD

**Issue by Eternally-god** [rong862/bear#86]
在抖音的点赞 评论与收藏按钮之下 还有一个不喜欢按钮（大概是随机出现的），能不能更新一下 隐藏掉这个非常多余的不喜欢按钮 很影响刷抖音

**Comment by rong862** [comment]
没发现有这个按钮！

**Comment by Eternally-god** [comment]
关于这个不喜欢按钮 是随机出现的（可以清除抖音的数据重新随机，不过 不太理想）
你可以在抖音搜索这个关键词 可以看到他们的截图很多都有这个不喜欢按钮

**Comment by Eternally-god** [comment]
> 没发现有这个按钮！

关于这个不喜欢按钮是随机出现的 可以通过清除抖音数据再次进行随机 不过 有些不太理想。
你也可以在抖音搜索这个关键词 可以看到他们的截图上很多都有这个不喜欢按钮
