### ISSUE TITLE
新版适配底部标签功能失效

### ISSUE THREAD

**Issue by aiopraks** [rong862/bear#88]

**Comment by rong862** [comment]
修复中

**Comment by aiopraks** [comment]
> 修复中

辛苦了

**Comment by nljxlove** [comment]
自带的自动播放每次都要手动开启，能不能加一个默认开启的开关。

**Comment by nljxlove** [comment]
![Screenshot_2023-10-10-08-09-28-293_com ss android ugc aweme](https://github.com/rong862/bear/assets/32213083/2de37532-7961-4c60-a766-5372f6758641)

**Comment by rong862** [comment]
更新
