### ISSUE TITLE
能不能适配全面屏的显示？

### ISSUE THREAD

**Issue by twamix** [rong862/bear#93]
目前的痘印在所有手机全面屏显示都会出现周围显示不全，只有调出来虚拟按键才可以显示完全，大佬能不能做个功能强制拉伸之类的 ？

**Comment by rong862** [comment]
这个视频比例问题，长度拉开了宽度也会拉到边界外。

**Comment by twamix** [comment]
能不能加个选项，保持默认的长宽，多余的用黑色代替

**Comment by rong862** [comment]
把状态栏和底部选项卡透明功能关闭就行了。
