### ISSUE TITLE
能把极速版也适配一下嘛😳

### ISSUE THREAD

**Issue by ec-to** [rong862/bear#95]
rt

**Comment by rong862** [comment]
已经适配完了，等下个版本；

**Comment by xiaoxiaoxiaodeseyixia** [comment]
> 已经适配完了，等下个版本；


大佬 极速版从哪个版本开始适配的😳

**Comment by ec-to** [comment]
> > 已经适配完了，等下个版本；
> 
> 大佬 极速版从哪个版本开始适配的😳

你直接下载最新版本，不就好了。
