### ISSUE TITLE
安卓14需要怎么处理才不闪退？

### ISSUE THREAD

**Issue by naoki66** [rong862/bear#98]
手机半夜自动升级到安卓14了，然后历史版本全试过了，都闪退。
已经用最新lspatch，加上最新模块，打包还是闪退。
小红书带模块，从安卓13升上来的却正常。不知道怎么处理了。

**Comment by ec-to** [comment]
一加coloros 安卓14也闪退。注入后也闪退。貌似不是个别现象

**Comment by rong862** [comment]
可能lspatch兼容问题，Android14直接使用没问题。

**Comment by ec-to** [comment]
> 可能lspatch兼容问题，Android14直接使用没问题。

我是lsposed，我在2.0.5已经不闪退了

**Comment by naoki66** [comment]
> > 可能lspatch兼容问题，Android14直接使用没问题。
> 
> 我是lsposed，我在2.0.5已经不闪退了

配合哪个版本不闪退？

**Comment by naoki66** [comment]
> 可能lspatch兼容问题，Android14直接使用没问题。

我是集成版本，暂时没有条件root

**Comment by ec-to** [comment]
> > 可能lspatch兼容问题，Android14直接使用没问题。
> 
> 我是集成版本，暂时没有条件root

那你这个闪退的原因太多了，有可能lsposed的原因注入，有可能抖音校验签名的原因。都有可能。安卓14才开始很多都不适配只能慢慢等
